services:
  - type: web
    name: campus-equipment-system
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: python -m gunicorn myproject.wsgi:application
    envVars:
      - key: SUPABASE_DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: "True"
      - key: WEB_CONCURRENCY
        value: "2"
      - key: PYTHON_VERSION
        value: "3.14.3"
