# Generated by Django 6.0.3 on 2026-04-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_borrowed_condition_transaction_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='role',
        ),
    ]
