# Generated by Django 6.0.3 on 2026-05-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Campus Equipment Borrowing & Monitoring System', max_length=255)),
                ('school_logo_url', models.URLField(blank=True)),
                ('borrow_limit', models.PositiveIntegerField(default=3)),
                ('overdue_grace_period_days', models.PositiveIntegerField(default=0)),
                ('reminder_days_before_due', models.PositiveIntegerField(default=1)),
                ('item_categories', models.TextField(blank=True, help_text='Comma-separated list of item categories such as AV, Lab, Sports, Tools.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='borrower',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
