from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    activity_log_list,
    dashboard,
    borrower_list, borrower_detail, borrower_create, borrower_edit, borrower_delete, borrower_archive_list, borrower_restore, borrower_purge,
    item_list, item_create, item_edit, item_delete, item_archive_list, item_restore, item_purge, item_qr_labels,
    borrow_item,
    return_list, return_item,
    transaction_list,
    transaction_receipt,
    report_list,
    logout_view,
    login_view,
    maintenance_list,
    register_view,
    staff_signup_view,
    user_edit,
    user_list,
    profile_view,
    create_system_backup,
    system_settings_view,
    user_toggle_status,
    user_reset_password,
    health_check,
    notification_list,
    public_item_availability,
    public_borrower_lookup,
    public_item_detail,
    run_notification_check,
)

urlpatterns = [
    path('public/items/', public_item_availability, name='public_item_availability'),
    path('public/items/detail/<int:pk>/', public_item_detail, name='public_item_detail'),
    path('public/borrower/', public_borrower_lookup, name='public_borrower_lookup'),
    path('', dashboard, name='dashboard'),

    path('borrowers/', borrower_list, name='borrower_list'),
    path('borrowers/<int:pk>/', borrower_detail, name='borrower_detail'),
    path('borrowers/archived/', borrower_archive_list, name='borrower_archive_list'),
    path('borrowers/add/', borrower_create, name='borrower_create'),
    path('borrowers/edit/<int:pk>/', borrower_edit, name='borrower_edit'),
    path('borrowers/delete/<int:pk>/', borrower_delete, name='borrower_delete'),
    path('borrowers/restore/<int:pk>/', borrower_restore, name='borrower_restore'),
    path('borrowers/purge/<int:pk>/', borrower_purge, name='borrower_purge'),

    path('items/', item_list, name='item_list'),
    path('items/qr-labels/', item_qr_labels, name='item_qr_labels'),
    path('items/archived/', item_archive_list, name='item_archive_list'),
    path('items/add/', item_create, name='item_create'),
    path('items/edit/<int:pk>/', item_edit, name='item_edit'),
    path('items/delete/<int:pk>/', item_delete, name='item_delete'),
    path('items/restore/<int:pk>/', item_restore, name='item_restore'),
    path('items/purge/<int:pk>/', item_purge, name='item_purge'),

    path('borrow/', borrow_item, name='borrow_item'),

    path('return/', return_list, name='return_list'),
    path('return/<int:pk>/', return_item, name='return_item'),

    path('transactions/', transaction_list, name='transaction_list'),
    path('transactions/<int:pk>/receipt/', transaction_receipt, name='transaction_receipt'),
    path('reports/', report_list, name='report_list'),
    path('activity-logs/', activity_log_list, name='activity_log_list'),
    path('notifications/', notification_list, name='notification_list'),
    path('notifications/run-check/', run_notification_check, name='run_notification_check'),
    path('users/', user_list, name='user_list'),
    path('settings/', system_settings_view, name='system_settings'),
    path('settings/backups/create/', create_system_backup, name='create_system_backup'),
    path('profile/', profile_view, name='profile'),
    path('users/edit/<int:pk>/', user_edit, name='user_edit'),
    path('users/toggle-status/<int:pk>/', user_toggle_status, name='user_toggle_status'),
    path('users/reset-password/<int:pk>/', user_reset_password, name='user_reset_password'),
    path('maintenance/', maintenance_list, name='maintenance_list'),
    path('health/', health_check, name='health_check'),

    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('staff-signup/', staff_signup_view, name='staff_signup'),
    path(
        'password-reset/',
        auth_views.PasswordResetView.as_view(template_name='core/password_reset_form.html'),
        name='password_reset',
    ),
    path(
        'password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'),
        name='password_reset_done',
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html'),
        name='password_reset_confirm',
    ),
    path(
        'password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'),
        name='password_reset_complete',
    ),
]
